I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/Day 2, Interaction 1.rpy", line 78, in script
    jump D2I2
ScriptError: could not find label 'D2I2'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/Day 2, Interaction 1.rpy", line 78, in script
    jump D2I2
  File "C:\Users\Cornelius\Desktop\renpy-7.2.2-sdk\renpy\ast.py", line 1678, in execute
    rv = renpy.game.script.lookup(target)
  File "C:\Users\Cornelius\Desktop\renpy-7.2.2-sdk\renpy\script.py", line 886, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'D2I2'.

Windows-8-6.2.9200
Ren'Py 7.2.2.491
Scenes From an Italian Cafe 0.10
Mon Nov 18 20:31:57 2019
