I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/Day 2, Interaction 3.rpy", line 130, in script
    jump D2I4
ScriptError: could not find label 'D2I4'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/Day 2, Interaction 3.rpy", line 130, in script
    jump D2I4
  File "C:\Users\Cornelius\Desktop\renpy-7.2.2-sdk\renpy\ast.py", line 1678, in execute
    rv = renpy.game.script.lookup(target)
  File "C:\Users\Cornelius\Desktop\renpy-7.2.2-sdk\renpy\script.py", line 886, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'D2I4'.

Windows-8-6.2.9200
Ren'Py 7.2.2.491
MAKE SOME HECKING COFFEE 1.0
Mon Nov 11 18:35:17 2019
