I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/Day 1 Outline.rpy", line 63, in script
    if Coffee == True:
  File "game/Day 1 Outline.rpy", line 63, in <module>
    if Coffee == True:
NameError: name 'Coffee' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/Day 1 Outline.rpy", line 63, in script
    if Coffee == True:
  File "C:\Users\Qrow99\Documents\renpy-7.3.3-sdk\renpy\ast.py", line 1832, in execute
    if renpy.python.py_eval(condition):
  File "C:\Users\Qrow99\Documents\renpy-7.3.3-sdk\renpy\python.py", line 2059, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\Qrow99\Documents\renpy-7.3.3-sdk\renpy\python.py", line 2052, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/Day 1 Outline.rpy", line 63, in <module>
    if Coffee == True:
NameError: name 'Coffee' is not defined

Windows-8-6.2.9200
Ren'Py 7.3.5.606
MAKE SOME HECKING COFFEE 1.0
Sat Nov 09 18:58:44 2019
